# Generated by Django 2.1.4 on 2018-12-10 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('images', models.ImageField(upload_to='')),
                ('status', models.CharField(choices=[('Expired', 'expired'), ('Accepted', 'accepted'), ('Pending', 'pending')], default='Pending', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civil_id', models.CharField(max_length=120)),
                ('phone_no', models.CharField(blank=True, max_length=120, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='accident',
            name='involved',
            field=models.ManyToManyField(to='traffic.Population'),
        ),
    ]
