# Generated by Django 2.1.4 on 2018-12-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('New', 'new'), ('Accepted', 'accepted'), ('Pending', 'pending'), ('Expired', 'expired')], default='New', max_length=120),
        ),
        migrations.AlterField(
            model_name='involved',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Declined', 'Declined'), ('No Response', 'No Response')], default='No response', max_length=120),
        ),
    ]
