# Generated by Django 2.1.4 on 2018-12-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Accepted', 'accepted'), ('New', 'new'), ('Expired', 'expired')], default='New', max_length=120),
        ),
        migrations.AlterField(
            model_name='involved',
            name='status',
            field=models.CharField(choices=[('Declined', 'Declined'), ('Accepted', 'Accepted'), ('No Response', 'No Response')], default='No Response', max_length=120),
        ),
    ]
