# Generated by Django 2.1.4 on 2018-12-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Expired', 'expired'), ('Accepted', 'accepted'), ('Pending', 'pending')], default='Pending', max_length=120),
        ),
    ]
