# Generated by Django 2.1.4 on 2018-12-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('New', 'new'), ('Accepted', 'accepted'), ('Expired', 'expired'), ('Pending', 'pending')], default='New', max_length=120),
        ),
    ]
