# Generated by Django 2.1.4 on 2018-12-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Expired', 'expired'), ('Accepted', 'accepted')], default='Pending', max_length=120),
        ),
    ]
