# Generated by Django 2.1.4 on 2018-12-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('New', 'new'), ('Expired', 'expired'), ('Accepted', 'accepted')], default='New', max_length=120),
        ),
        migrations.AlterField(
            model_name='accident',
            name='status_for_staff',
            field=models.CharField(blank=True, choices=[('Accepted', 'accepted'), ('Declined', 'declined')], max_length=120, null=True),
        ),
    ]
