# Generated by Django 2.1.4 on 2018-12-16 06:42

from django.db import migrations, models
import traffic.validators


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='accident_image',
            field=models.FileField(default='1', upload_to='../media/', validators=[traffic.validators.validate_file_extension]),
        ),
    ]
