# Generated by Django 2.1.4 on 2018-12-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_auto_20181216_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Expired', 'expired'), ('Accepted', 'accepted'), ('Pending', 'pending')], default='Pending', max_length=120),
        ),
    ]
