# Generated by Django 2.1.4 on 2018-12-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_auto_20181226_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Accepted', 'accepted'), ('Expired', 'expired'), ('New', 'new'), ('Pending', 'pending')], default='New', max_length=120),
        ),
        migrations.AlterField(
            model_name='involved',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Declined', 'Declined'), ('No Response', 'No Response')], default='No Response', max_length=120),
        ),
    ]
