# Generated by Django 2.1.4 on 2018-12-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_auto_20181226_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Expired', 'expired'), ('Pending', 'pending'), ('Accepted', 'accepted'), ('New', 'new')], default='New', max_length=120),
        ),
        migrations.AlterField(
            model_name='involved',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('No Response', 'No Response'), ('Declined', 'Declined')], default='No response', max_length=120),
        ),
    ]
