# Generated by Django 2.1.4 on 2018-12-12 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_auto_20181211_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_image1', models.ImageField(upload_to='')),
                ('car_image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('car_image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('car_image4', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regist_image1', models.ImageField(upload_to='')),
                ('regist_image2', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='accident',
            name='images',
        ),
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Expired', 'expired'), ('Accepted', 'accepted'), ('Pending', 'pending')], default='Pending', max_length=120),
        ),
        migrations.AddField(
            model_name='registrationimage',
            name='accident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic.Accident'),
        ),
        migrations.AddField(
            model_name='carimage',
            name='accident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic.Accident'),
        ),
    ]
