# Generated by Django 2.1.4 on 2018-12-18 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_auto_20181216_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detective', models.CharField(max_length=120)),
                ('examiner', models.CharField(max_length=120)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Accepted', 'accepted'), ('Expired', 'expired'), ('Pending', 'pending')], default='Pending', max_length=120),
        ),
        migrations.AddField(
            model_name='report',
            name='accident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='traffic.Accident'),
        ),
    ]
