# Generated by Django 2.1.4 on 2018-12-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_auto_20181210_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Expired', 'expired'), ('Accepted', 'accepted')], default='Pending', max_length=120),
        ),
        migrations.AlterField(
            model_name='population',
            name='phone_no',
            field=models.TextField(blank=True, null=True),
        ),
    ]
