# Generated by Django 2.1.4 on 2018-12-24 07:19

from django.db import migrations, models
import django.db.models.deletion
import traffic.validators


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_auto_20181223_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
                ('involved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic.Profile')),
            ],
        ),
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Expired', 'expired'), ('New', 'new'), ('Pending', 'pending'), ('Accepted', 'accepted')], default='New', max_length=120),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='accident_image',
            field=models.TextField(validators=[traffic.validators.validate_file_extension]),
        ),
    ]
