# Generated by Django 2.1.4 on 2018-12-12 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_auto_20181212_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carimage',
            old_name='car_image1',
            new_name='car_image',
        ),
        migrations.RemoveField(
            model_name='carimage',
            name='car_image2',
        ),
        migrations.RemoveField(
            model_name='carimage',
            name='car_image3',
        ),
        migrations.RemoveField(
            model_name='carimage',
            name='car_image4',
        ),
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Expired', 'expired'), ('Pending', 'pending'), ('Accepted', 'accepted')], default='Pending', max_length=120),
        ),
        migrations.AlterField(
            model_name='registrationimage',
            name='accident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='traffic.Accident'),
        ),
    ]
