# Generated by Django 2.1.4 on 2018-12-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_auto_20181216_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Expired', 'expired'), ('Pending', 'pending'), ('Accepted', 'accepted')], default='Pending', max_length=120),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='accident_image',
            field=models.FileField(upload_to=''),
        ),
    ]
