# Generated by Django 2.1.4 on 2018-12-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_auto_20181222_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Expired', 'expired'), ('Accepted', 'accepted'), ('New', 'new')], default='New', max_length=120),
        ),
        migrations.AlterField(
            model_name='accident',
            name='status_for_staff',
            field=models.CharField(blank=True, choices=[('Accepted', 'accepted'), ('Declined', 'declined')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='civil_id',
            field=models.CharField(max_length=120),
        ),
    ]
