# Generated by Django 2.1.4 on 2018-12-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_auto_20181227_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Expired', 'expired'), ('New', 'new'), ('Pending', 'pending'), ('Accepted', 'accepted')], default='New', max_length=120),
        ),
        migrations.AlterField(
            model_name='involved',
            name='status',
            field=models.CharField(choices=[('Declined', 'Declined'), ('No Response', 'No Response'), ('Accepted', 'Accepted')], default='No Response', max_length=120),
        ),
    ]
