# Generated by Django 2.1.4 on 2018-12-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0004_auto_20181227_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('New', 'new'), ('Expired', 'expired'), ('Accepted', 'accepted'), ('Pending', 'pending')], default='New', max_length=120),
        ),
        migrations.AlterField(
            model_name='involved',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('No Response', 'No Response'), ('Declined', 'Declined')], default='No Response', max_length=120),
        ),
    ]
