# Generated by Django 2.1.4 on 2018-12-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0004_auto_20181222_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='description',
            field=models.TextField(default='accident'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('New', 'new'), ('Expired', 'expired'), ('Pending', 'pending'), ('Accepted', 'accepted')], default='New', max_length=120),
        ),
        migrations.AlterField(
            model_name='accident',
            name='status_for_staff',
            field=models.CharField(blank=True, choices=[('Declined', 'declined'), ('Accepted', 'accepted')], max_length=120, null=True),
        ),
    ]
