# Generated by Django 2.1.4 on 2018-12-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0004_auto_20181216_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Accepted', 'accepted'), ('New', 'new'), ('Expired', 'expired')], default='Pending', max_length=120),
        ),
    ]
