# Generated by Django 2.1.4 on 2018-12-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0004_auto_20181216_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Expired', 'expired'), ('Accepted', 'accepted'), ('Pending', 'pending')], default='Pending', max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='civil_id',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
