# Generated by Django 2.1.4 on 2018-12-19 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0004_auto_20181219_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reported_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
