# Generated by Django 2.1.4 on 2018-12-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0004_auto_20181212_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carimage',
            old_name='car_image',
            new_name='accident_image',
        ),
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Expired', 'expired'), ('Accepted', 'accepted')], default='Pending', max_length=120),
        ),
    ]
