# Generated by Django 2.1.4 on 2018-12-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0004_auto_20181224_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='involved',
        ),
        migrations.AddField(
            model_name='involved',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Accepted', 'accepted'), ('Expired', 'expired'), ('New', 'new')], default='New', max_length=120),
        ),
        migrations.AlterField(
            model_name='involved',
            name='status',
            field=models.CharField(choices=[('No Response', 'No Response'), ('Declined', 'Declined'), ('Accepted', 'Accepted')], default='No response', max_length=120),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
