# Generated by Django 2.1.4 on 2018-12-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0005_auto_20181227_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Expired', 'expired'), ('New', 'new'), ('Accepted', 'accepted'), ('Pending', 'pending')], default='New', max_length=120),
        ),
        migrations.AlterField(
            model_name='involved',
            name='status',
            field=models.CharField(choices=[('No Response', 'No Response'), ('Declined', 'Declined'), ('Accepted', 'Accepted')], default='No Response', max_length=120),
        ),
    ]
