# Generated by Django 2.1.4 on 2018-12-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0005_auto_20181216_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Expired', 'expired'), ('Accepted', 'accepted'), ('New', 'new'), ('Pending', 'pending')], default='Pending', max_length=120),
        ),
    ]
