# Generated by Django 2.1.4 on 2018-12-12 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0005_auto_20181212_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationimage',
            old_name='regist_image1',
            new_name='regist_image',
        ),
        migrations.RemoveField(
            model_name='registrationimage',
            name='regist_image2',
        ),
    ]
