# Generated by Django 2.1.4 on 2018-12-13 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0006_auto_20181212_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Expired', 'expired'), ('Pending', 'pending'), ('Accepted', 'accepted')], default='Pending', max_length=120),
        ),
        migrations.AlterField(
            model_name='registrationimage',
            name='accident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic.Accident'),
        ),
    ]
