# Generated by Django 2.1.4 on 2018-12-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0006_auto_20181227_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Accepted', 'accepted'), ('Expired', 'expired'), ('New', 'new'), ('Pending', 'pending')], default='New', max_length=120),
        ),
        migrations.AlterField(
            model_name='involved',
            name='status',
            field=models.CharField(choices=[('Declined', 'Declined'), ('Accepted', 'Accepted'), ('No Response', 'No Response')], default='No Response', max_length=120),
        ),
    ]
