# Generated by Django 2.1.4 on 2018-12-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0007_auto_20181227_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Expired', 'expired'), ('New', 'new'), ('Accepted', 'accepted')], default='New', max_length=120),
        ),
        migrations.AlterField(
            model_name='involved',
            name='status',
            field=models.CharField(choices=[('No Response', 'No Response'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='No Response', max_length=120),
        ),
    ]
