# Generated by Django 2.1.4 on 2018-12-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0007_auto_20181213_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Accepted', 'accepted'), ('Pending', 'pending'), ('Expired', 'expired')], default='Pending', max_length=120),
        ),
    ]
