# Generated by Django 2.1.4 on 2018-12-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0008_auto_20181217_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='status_for_staff',
            field=models.CharField(choices=[('Accepted', 'accepted'), ('Pending', 'pending'), ('Expired', 'expired'), ('New', 'new')], default='Pending', max_length=120),
        ),
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Accepted', 'accepted'), ('Pending', 'pending'), ('Expired', 'expired'), ('New', 'new')], default='Pending', max_length=120),
        ),
    ]
