# Generated by Django 2.1.4 on 2018-12-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0008_auto_20181213_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='location',
        ),
        migrations.AddField(
            model_name='accident',
            name='location_latitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
        ),
        migrations.AddField(
            model_name='accident',
            name='location_longitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
        ),
    ]
