# Generated by Django 2.1.4 on 2018-12-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0008_auto_20181227_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Accepted', 'accepted'), ('Pending', 'pending'), ('Expired', 'expired'), ('New', 'new')], default='New', max_length=120),
        ),
        migrations.AlterField(
            model_name='involved',
            name='status',
            field=models.CharField(choices=[('Declined', 'Declined'), ('No Response', 'No Response'), ('Accepted', 'Accepted')], default='No Response', max_length=120),
        ),
    ]
