# Generated by Django 2.1.4 on 2018-12-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0009_auto_20181217_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Accepted', 'accepted'), ('New', 'new'), ('Pending', 'pending'), ('Expired', 'expired')], default='Pending', max_length=120),
        ),
        migrations.AlterField(
            model_name='accident',
            name='status_for_staff',
            field=models.CharField(blank=True, choices=[('Accepted', 'accepted'), ('Declined', 'declined')], max_length=120, null=True),
        ),
    ]
