# Generated by Django 2.1.4 on 2018-12-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0009_auto_20181227_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Expired', 'expired'), ('Accepted', 'accepted'), ('Pending', 'pending'), ('New', 'new')], default='New', max_length=120),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='accident_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
