# Generated by Django 2.1.4 on 2018-12-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0009_auto_20181226_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Expired', 'expired'), ('Accepted', 'accepted'), ('New', 'new')], default='New', max_length=120),
        ),
        migrations.AlterField(
            model_name='involved',
            name='status',
            field=models.CharField(choices=[('Declined', 'Declined'), ('Accepted', 'Accepted'), ('No Response', 'No Response')], default='No response', max_length=120),
        ),
    ]
