# Generated by Django 2.1.4 on 2018-12-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0010_auto_20181226_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('New', 'new'), ('Accepted', 'accepted'), ('Expired', 'expired'), ('Pending', 'pending')], default='New', max_length=120),
        ),
        migrations.AlterField(
            model_name='involved',
            name='status',
            field=models.CharField(choices=[('Declined', 'Declined'), ('No Response', 'No Response'), ('Accepted', 'Accepted')], default='No response', max_length=120),
        ),
    ]
