# Generated by Django 2.1.4 on 2019-01-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0011_auto_20181227_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Expired', 'expired'), ('New', 'new'), ('Pending', 'pending'), ('Accepted', 'accepted')], default='New', max_length=120),
        ),
        migrations.AlterField(
            model_name='involved',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('No Response', 'No Response'), ('Declined', 'Declined')], default='No Response', max_length=120),
        ),
    ]
