# Generated by Django 2.1.4 on 2018-12-19 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0008_auto_20181219_1332'),
        ('traffic', '0011_auto_20181217_1257'),
    ]

    operations = [
    ]
