# Generated by Django 2.1.4 on 2018-12-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0012_merge_20181219_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Expired', 'expired'), ('Accepted', 'accepted'), ('Pending', 'pending'), ('New', 'new')], default='New', max_length=120),
        ),
        migrations.AlterField(
            model_name='accident',
            name='status_for_staff',
            field=models.CharField(blank=True, choices=[('Declined', 'declined'), ('Accepted', 'accepted')], max_length=120, null=True),
        ),
    ]
