# Generated by Django 2.1.4 on 2018-12-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0013_auto_20181219_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='status_for_staff',
        ),
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('New', 'new'), ('Accepted', 'accepted'), ('Expired', 'expired'), ('Pending', 'pending')], default='New', max_length=120),
        ),
    ]
