# Generated by Django 2.1.4 on 2018-12-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0014_auto_20181220_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Expired', 'expired'), ('New', 'new'), ('Pending', 'pending'), ('Accepted', 'accepted')], default='New', max_length=120),
        ),
    ]
