# Generated by Django 2.1.4 on 2018-12-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0005_report_reported_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Accepted', 'accepted'), ('Expired', 'expired'), ('Pending', 'pending')], default='Pending', max_length=120),
        ),
    ]
