# Generated by Django 2.1.4 on 2018-12-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0006_auto_20181219_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
