# Generated by Django 2.1.4 on 2018-12-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0007_report_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report',
        ),
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('Expired', 'expired'), ('Pending', 'pending'), ('Accepted', 'accepted')], default='Pending', max_length=120),
        ),
    ]
